### ISSUE TITLE
Emitted parameters are wrong

### ISSUE THREAD

**Issue by riverar** [WalkingCat/MetaDiff#1]
When looking at a diff between Windows 10 17643 and 17639, for example, the parameters emitted for various methods and functions are incorrect.

Example from MetaDiff:
```
+ public class Windows.UI.Xaml.Hosting.XamlBridge {
...
+   public static XamlBridge CreateForParentHwnd( int result, ref int parentHwnd );
+ }
```

Example from Ildasm:
```
  .method /*06003172*/ public hidebysig newslot abstract virtual 
          instance class Windows.UI.Xaml.Hosting.XamlBridge/*01000840*/ 
          CreateForParentHwnd([in] int32 parentHwnd,
                              [out] int32& hostHwnd) cil managed
```

I was poking around MetaDiff code and `enum_params` appears to incorrectly retrieve 3 params (https://github.com/WalkingCat/MetaDiff/blob/master/meta_reader.cpp#L276-L277). `parse_method` (https://github.com/WalkingCat/MetaDiff/blob/master/meta_sig_parser.cpp#L33) appears to retrieve a calling convention of `thiscall` which is also incorrect.

I suspect something is slightly off when reading the token stream and MetaDiff is mixing the metadata of two methods together. Or perhaps this is an external COR API bug?

**Comment by riverar** [comment]
`metadiff -o old\Windows.UI.Xaml.winmd -n new\Windows.UI.Xaml.winmd`
Test files: [test_metadata.zip](https://github.com/WalkingCat/MetaDiff/files/1935319/test_metadata.zip)

**Comment by WalkingCat** [comment]
thanks for reporting, will look into it

**Comment by riverar** [comment]
Some further information:

I compared the `sig` with ildasm dump and it appears MetaDiff is looking at a private virtual method (as part of `IXamlBridgeStatics`) for some reason. (I'm not using the non-public flag.)

```
.class /*02000835*/ interface private abstract auto ansi windowsruntime Windows.UI.Xaml.Hosting.IXamlBridgeStatics
{
...
  .method /*06003172*/ public hidebysig newslot abstract virtual 
          instance class Windows.UI.Xaml.Hosting.XamlBridge/*01000840*/ 
          CreateForParentHwnd([in] int32 parentHwnd,
                              [out] int32& hostHwnd) cil managed
  // SIG: 20 02 12 A1 01 08 10 08
```

If you add a `if (ret->name == L"CreateForParentHwnd") DebugBreak();` to `get_method`, you'll get the sig match above.

Hope that helps!

**Comment by WalkingCat** [comment]
thank you so much for your efforts and nice hints :-)
I'll look into it later, but while you are at it, could you try to look at this file ?
https://github.com/WalkingCat/MetaDiff/blob/master/meta_reader.cpp
there are several ways to init the MetaDataDispenser, as in the "init" and "init_alt" (commented) functions, could you try to use different methods and see if there is any difference ? 😃
